# Learn more about configuring your Shopify app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "privacy-popup"
client_id = "{{ SHOPIFY_API_KEY }}"
application_url = "https://privacy-popup.q-biz.co.il"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_themes,read_themes"

[auth]
redirect_urls = [
  "https://privacy-popup.q-biz.co.il/auth/callback",
  "https://privacy-popup.q-biz.co.il/auth/shopify/callback",
  "https://privacy-popup.q-biz.co.il/api/auth/callback"
]

[webhooks]
api_version = "2024-10"

[pos]
embedded = false

[[webhooks.subscriptions]]
topics = ["app/uninstalled"]
uri = "/api/webhooks/app/uninstalled"

[build]
automatically_update_urls_on_dev = true
dev_store_url = "{{ DEVELOPMENT_STORE_URL }}"
include_config_on_deploy = true
